### ISSUE TITLE
"libcells" no such variable when using `sta::parse_port_net_args`

### ISSUE THREAD

**Issue by gadfort** [parallaxsw/OpenSTA#100]
When using `sta::parse_port_net_args` I sometimes get the following error:
```
14 can't read "libcells": no such variable
```
As best I can tell I think this is the line that it is coming from: https://github.com/parallaxsw/OpenSTA/blob/64f3c0d7583a9626087002c19818b79a9242223d/tcl/CmdArgs.tcl#L81

I've attached a testcase [sta-test.tar.gz](https://github.com/user-attachments/files/17114671/sta-test.tar.gz)

To run it:
```
tar xvf sta-test.tar.gz
cd sta-test
sta -exit run.tcl
```

Should produce:
```
OpenSTA 2.6.0 20925bb009 Copyright (c) 2024, Parallax Software, Inc.
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>

This is free software, and you are free to change and redistribute it
under certain conditions; type `show_copying' for details. 
This program comes with ABSOLUTELY NO WARRANTY; for details type `show_warranty'.
Error: run.tcl, 14 can't read "libcells": no such variable
```

**Comment by jjcherry56** [comment]
fixed by daff3715 issue100 parse_port_net_args
