### ISSUE TITLE
Bug: mark wrong clock pin in findClkPins()

### ISSUE THREAD

**Issue by wuheng01** [parallaxsw/OpenSTA#12]
The logic of marking clock pins is to start from the source of clock, then Bfs forward, and mark them in sequence.

For the following logical structure, our opensta will mark `reg2/D` as clock pin. This is actually unreasonable, especially when `reg2/CK` has been driven by other clocks. CLK_BUF2 should be considered as the end of the clock of CLK_A. `CLK_BUF2->BUF_1->reg2/D` should be considered as the data path.
Of course, there is no problem with reg1/CK being recognized as the clock pin.
![image](https://github.com/The-OpenROAD-Project/OpenSTA/assets/64893282/b5cc9fc0-58ff-42d4-840c-9edb9ca34f17)

from issue https://github.com/The-OpenROAD-Project/OpenSTA/issues/232

**Comment by jjcherry56** [comment]
I don't see it as unreasonable. OpenSTA's definition of the clock network is the combinational fanout of the clock source, which includes reg2/D. There is nothing that precludes a clock signal being used as data, as in your example. OpenSTA will report the timing check at reg2 correctly. If there is a functional problem with OpenSTA then you need to submit a test case that demonstrates the issue.
