### ISSUE TITLE
`is_memory` property could be more sensitive

### ISSUE THREAD

**Issue by akashlevy** [parallaxsw/OpenSTA#124]
For a Liberty cell, `is_memory` is only true if `is_memory : true` attribute is on the cell. But I've found many cases in the wild where that attribute is missing for RAMs/ROMs. Instead, these cells have a `memory () { ... }` group, which definitively marks them as being memories. Would it make sense to check for `memory () { ... }` as another possible condition for the `is_memory` property?

Let me know if you'd like me to implement and PR this.

**Comment by parallaxsw** [comment]
Is there other functionality in the cell or is it just have a memory group?
A complex cell can have a memory group as well as other functionality so it is more like
has-a instead of is-a.
Maybe make a has_memory predicate that is true for either case.

**Comment by akashlevy** [comment]
Makes sense--can make a PR for `has_memory` at some point
