### ISSUE TITLE
Suggestion: rename `-group_count` and `-endpoint_count` in `report_checks`

### ISSUE THREAD

**Issue by akashlevy** [parallaxsw/OpenSTA#126]
The naming for `-group_count` and `-endpoint_count` in `report_checks` is a bit unintuitive.

To me, the flag names seem to suggest that `-group_count` would set *the total number of path groups that get reported*, and `-endpoint_count` would set *the total number of endpoints that get reported*. Instead, `-group_count` sets the number of paths per path group and `-endpoint_count` sets the number of paths per endpoint.

I would consider renaming these flags to avoid end user confusion. Perhaps something more explicit like `-group_count`->`-paths_per_group` and `-endpoint_count`->`-paths_per_endpoint`.

Of course, you would probably want to still accept `-group_count` and `-endpoint_count` for backwards-compatibility.

Just a small suggestion. Let me know your thoughts.

**Comment by parallaxsw** [comment]
I agree the names are terrible. Another option is -group_path_count, -endpoint_path_count.

**Comment by akashlevy** [comment]
Those names sounds nice to me. Shall I make a PR for this or do you want to take care of it?

**Comment by parallaxsw** [comment]
go for it

**Comment by akashlevy** [comment]
I should still allow `-group_count` and `-endpoint_count` for backwards compatibility, right?

**Comment by parallaxsw** [comment]
Right; add warnings for them (grep deprecated */*.tcl for examples)
