### ISSUE TITLE
Why Sdc::ensureClkGroupExclusions() not do one time init like before?

### ISSUE THREAD

**Issue by AlpacaYin** [parallaxsw/OpenSTA#13]
Every time step into ensureClkGroupExclusions, it will always do makeClkGroupExclusions which may cost a lot in multiClock cases.
```
void
Sdc::ensureClkGroupExclusions()
{
  for (auto name_clk_groups : clk_groups_name_map_)
    makeClkGroupExclusions(name_clk_groups.second);
}
```
https://github.com/The-OpenROAD-Project/OpenSTA/commit/3f7df84fb88c9d0c9bbbf15626fd6347e1e9d9bf#diff-55009e450ec9f5160f98d7f86d9b9bf4643022dfea14228b8d2b8e9846289bfe
![image](https://github.com/parallaxsw/OpenSTA/assets/139737573/a6929aeb-d153-4c9a-8727-c515118f1a97)
I see code change here.Seems strange.

**Comment by jjcherry56** [comment]
The number of clocks is irrelevant; the run time depends on the number of clock groups.
You are correct, it should check to see if the group exclusions are empty before it runs.
commit 43631751 Sdc::ensureClkGroupExclusions check if necessary
adds the check.
