### ISSUE TITLE
Question: Why is `propagate_all_clocks` disabled by default?

### ISSUE THREAD

**Issue by akashlevy** [parallaxsw/OpenSTA#137]
It seems that most commercial tools propagate clocks automatically. Are there any gotchas to look out for when enabling this flag?

**Comment by jjcherry56** [comment]
I believe when Fred Flintstone was using opensta way back when the commercial tools he also used defaulted to ideal clocks, at least for the timer linked to synthesis. No gotchas really, just compatibility issues that apparently have changed.

**Comment by akashlevy** [comment]
Thanks! :)
