### ISSUE TITLE
SDC set_units prefix processing

### ISSUE THREAD

**Issue by sheblaev** [parallaxsw/OpenSTA#14]
Hi,
The SDC command set_units has the syntax:
set_units [-time time_unit] [-capacitance cap_unit] [-resistance res_unit]
   [-voltage voltage_unit] [-current current_unit] [-power power_unit]
   [-distance distance_unit]

The major tools like DC and Genus can add prefixes to units (examples from docs and internet):
![image](https://github.com/parallaxsw/OpenSTA/assets/9824885/a7f29e87-4287-4b2e-82f2-91454c7036be)

![image](https://github.com/parallaxsw/OpenSTA/assets/9824885/e8eacaaa-e759-41f4-b69a-0ab7a327ef54)

But the OpenSTA (build: OpenSTA 2.5.0 1740c894b4 from github.com) fails:
![image](https://github.com/parallaxsw/OpenSTA/assets/9824885/5de55959-04f9-4ed9-9ef6-ec7ce9e07e27)

Could you please consider the patch with prefix processing for tcl/Sdc.tcl ? The patch is in the attachment
[sdc.patch](https://github.com/parallaxsw/OpenSTA/files/14571995/sdc.patch)

**Comment by jjcherry56** [comment]
Makes sense to me. I couldn't get your patch file to work as is with either patch or git apply so I couldn't test it. Why don't you submit a pull request for it?

**Comment by sheblaev** [comment]
I see the issue is fixed by commit 105a078324d02efe041596a2d27a992c4420f7f8
Thanks!
