### ISSUE TITLE
Dcalc tolerance improperly considered in path enumeration

### ISSUE THREAD

**Issue by povik** [parallaxsw/OpenSTA#148]
See
https://github.com/parallaxsw/OpenSTA/blob/fded1f247dd3b1d6db524a7eeda7f941160e33a3/search/PathVertex.cc#L399

The `dcalc_tol_` value is relative tolerance, but it's compared against `to_arrival - path_arrival_` which I think is an absolute time difference.

**Comment by jjcherry56** [comment]
That is definitely broken. My experiments with fixing did not work properly; it means another close "wrong" path is considered the previous path. I think the dcalc tolerance support 
has to be thrown out.

**Comment by povik** [comment]
Why throw all of it out?

It seems to me we can avoid issues as long as we (1) use the tolerance to reduce the number of slew-induced changes in delay annotations and (2) keep arrivals perfectly consistent with delay annotations with no room for tolerance (up to machine precision). When we do that, there are no issues with recovering paths, and at least for the OpenROAD use case we still save runtime.

I have the patch below which seems to work:

```
diff --git a/dcalc/GraphDelayCalc.cc b/dcalc/GraphDelayCalc.cc
index 9b34acb..4645dcb 100644
--- a/dcalc/GraphDelayCalc.cc
+++ b/dcalc/GraphDelayCalc.cc
@@ -1112,9 +1112,10 @@ GraphDelayCalc::annotateDelaySlew(Edge *edge,
     float prev_gate_delay1 = delayAsFloat(prev_gate_delay);
     if (prev_gate_delay1 == 0.0
         || (abs(gate_delay1 - prev_gate_delay1) / prev_gate_delay1
-            > incremental_delay_tolerance_))
+            > incremental_delay_tolerance_)) {
       delay_changed = true;
-    graph_->setArcDelay(edge, arc, ap_index, gate_delay);
+      graph_->setArcDelay(edge, arc, ap_index, gate_delay);
+    }
   }
   return delay_changed;
 }
diff --git a/search/PathVertex.cc b/search/PathVertex.cc
index 0a1880e..09b5388 100644
--- a/search/PathVertex.cc
+++ b/search/PathVertex.cc
@@ -395,9 +395,7 @@ PrevPathVisitor::visitFromToPath(const Pin *,
   PathAPIndex path_ap_index = path_ap->index();
   if (to_rf->index() == path_rf_index_
       && path_ap_index == path_ap_index_
-      && (dcalc_tol_ > 0.0 
-         ? std::abs(delayAsFloat(to_arrival - path_arrival_)) < dcalc_tol_
-         : delayEqual(to_arrival, path_arrival_))
+      && delayEqual(to_arrival, path_arrival_)
       && (tagMatch(to_tag, path_tag_, this)
          // If the filter exception became active searching from
          // from_path to to_path the tag includes the filter, but

```

**Comment by jjcherry56** [comment]
Agreed. My mistake was trying to apply the tolerance to slews.
See ec009543 dcalc tolerance

**Comment by povik** [comment]
Thanks for resolving the path lookup issue. I've now had a chance to test incremental tolerance with repair_timing again.

> My mistake was trying to apply the tolerance to slews.

I don't understand the issue with applying tolerance to slews. As far as I can tell slew tolerance is more interesting than delay tolerance, since only slew tolerance stops the downstream propagation of delay recomputation, and delay recomputation is the costliest part of incremental STA in my experiments.

On current head of OpenSTA, I get negligible speed-up on repair_timing from higher tolerance. With the patch below (which applies the tolerance to slews instead of delays) I can save ~20 % from setting tolerance to 0.002.

```
diff --git a/dcalc/GraphDelayCalc.cc b/dcalc/GraphDelayCalc.cc
index 366af21d..0f950775 100644
--- a/dcalc/GraphDelayCalc.cc
+++ b/dcalc/GraphDelayCalc.cc
@@ -630,7 +630,12 @@ GraphDelayCalc::loadSlewsChanged(DrvrLoadSlews &load_slews_prev,
     const SlewSeq slews = graph_->slews(load_vertex);
     const SlewSeq  &slews_prev = load_slews_prev[index];
     for (size_t i = 0; i < slews.size(); i++) {
-      if (!delayEqual(slews[i], slews_prev[i]))
+      float prev_slew = delayAsFloat(slews_prev[i]);
+      float slew = delayAsFloat(slews[i]);
+
+      if ((prev_slew == 0.0 && slew != 0.0)
+          || (prev_slew != 0.0
+              && abs((slew - prev_slew) / prev_slew) > incremental_delay_tolerance_))
         return true;
     }
   }
@@ -1107,9 +1112,7 @@ GraphDelayCalc::annotateDelaySlew(Edge *edge,
     const ArcDelay &prev_gate_delay = graph_->arcDelay(edge,arc,ap_index);
     float gate_delay1 = delayAsFloat(gate_delay);
     float prev_gate_delay1 = delayAsFloat(prev_gate_delay);
-    if (prev_gate_delay1 == 0.0
-        || (abs(gate_delay1 - prev_gate_delay1) / prev_gate_delay1
-            > incremental_delay_tolerance_)) {
+    if (!delayEqual(gate_delay1, prev_gate_delay1)) {
       delay_changed = true;
       graph_->setArcDelay(edge, arc, ap_index, gate_delay);
     }
```

**Comment by calewis** [comment]
@jjcherry56 I independently discovered a similar idea where making the slews even more approximately equal, leads to a decent speed up.   I'm mostly trying to revive this discussion, to see if we can spend less time in delay calculations.
```
bool
GraphDelayCalc::loadSlewsChanged(DrvrLoadSlews &load_slews_prev,
                                 LoadPinIndexMap &load_pin_index_map)
{
  auto approximate_equal = [](float a, float b, float rel_tol = 1e-5,
                              float abs_tol = 1e-9) {
    return std::abs(a - b) <=
           std::max(rel_tol * std::max(std::abs(a), std::abs(b)), abs_tol);
  };

  size_t slew_count = graph_->slewCount();
  for (auto const [pin, index] : load_pin_index_map) {
    Vertex *load_vertex = graph_->pinLoadVertex(pin);
    SlewSeq &slews_prev = load_slews_prev[index];;
    const Slew *slews = load_vertex->slews();
    for (size_t i = 0; i < slew_count; i++) {
      if (!approximate_equal(slews[i], slews_prev[i])) return true;
    }
  }
  return false;
}
```

**Comment by calewis** [comment]
> Good luck trying to find error bars for pi model reduction or any of the multitude of delay calculators. Max error? Median error? Average error? I have regressions the shmoo wires and report them all but it doesn't really tell you what you see in a real design. The "error" depends on the wire topologies. I have never been willing to stick my neck out and declare an "error margin" for delay calculation. Only a marketing bozo can do that.

Surely we can do better than nothing although it might not be easy.  It seems that pi model errors are not so large as to be unusable for example.   STA already assumes that slews with a relative difference of 1e-6 or less are equal, surely there are situations where that can be relaxed, but to do that it'd be helpful to know when NLDM errors + Pi model errors >> slew_differences.
