### ISSUE TITLE
trivial crash on make_port without a design

### ISSUE THREAD

**Issue by maliberty** [parallaxsw/OpenSTA#149]
% sta
OpenSTA 2.6.0 aa598a2f14 Copyright (c) 2024, Parallax Software, Inc.
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>

This is free software, and you are free to change and redistribute it
under certain conditions; type `show_copying' for details. 
This program comes with ABSOLUTELY NO WARRANTY; for details type `show_warranty'.
sta [~/w2/tools/OpenROAD/test] make_port x y
Segmentation fault (core dumped)

**Comment by jjcherry56** [comment]
a06c4fc7 issue 149, 150, cmdNetwork->Sta::ensureLinked check libs
