### ISSUE TITLE
check_setup reports unconstrained endpoints for constant outputs

### ISSUE THREAD

**Issue by gadfort** [parallaxsw/OpenSTA#15]
I noticed that `check_setup` reports constant driven outputs as unconstrained endpoints. I'm not use if that makes sense since it's a constant. This might be on purpose, but it's not an actionable warning for the user so it causes some confusion.

I added a testcase in case you want to take a look.
```
tar xvf check_setup.tar.gz
sta sta.tcl
```
[check_setup.tar.gz](https://github.com/parallaxsw/OpenSTA/files/14574020/check_setup.tar.gz)

**Comment by jjcherry56** [comment]
Righto. I pushed a fix for this (and input delays)
5acc5db9 master check_setup input/output delays not required on constant ports
