### ISSUE TITLE
Fix error: unused variable ‘network’ [-Werror=unused-variable]

### ISSUE THREAD

**Issue by alaindargelas** [parallaxsw/OpenSTA#156]
On Ubuntu, with gcc -Werror flag on, there is a compilation error on an unused var.
I proposed a fix here:
https://github.com/Silimate/OpenSTA/pull/3

**Comment by akashlevy** [comment]
Issue appears to exist on macOS too

**Comment by jjcherry56** [comment]
no problem to fix but I'd like to know what you did to the cmake file to get the warning to show up,
since I never saw it with the current cmake file.

**Comment by jjcherry56** [comment]
3dd38ad1  Network.i [net capacitance] unused var

**Comment by akashlevy** [comment]
`-Werror` in `CMAKE_CXX_FLAGS` makes warnings errors. We have this in our environment

**Comment by akashlevy** [comment]
Thanks for the fix :)

**Comment by jjcherry56** [comment]
No, we are talking about an unused variable, not function.
-Wall impled -Wunused, which reports the warnings for "normal" source files.
But it does not report it for the swig file, which is where this one slipped by.
I know about -Werror but am not interested in it. I want to know how you got the
warning that for the swig file that turned into an error with -Werror.

**Comment by akashlevy** [comment]
We see these compiler errors when we include OpenSTA in https://github.com/Silimate/silisizer . I think it has something to do with the fact that we are using the Network API outside of OpenSTA, but I don't know enough about SWIG to tell you why it being external affects anything.

**Comment by alaindargelas** [comment]
Our CMake sets it here:
https://github.com/Silimate/silisizer/blob/0a81ee9a134cf481253e2f2d1dfeefefe5c427ee/CMakeLists.txt#L40
And it gets propagated to yours.
