### ISSUE TITLE
Incorrect port/cell names returned with get_ports/get_nets/get_cells command.

### ISSUE THREAD

**Issue by sagarbaba** [parallaxsw/OpenSTA#159]
I was trying the delay_calc.tcl script, following which I tried to query the ports/cells/nets. But, I see obfuscated names as below:
%%%%%%%%%%
sta [~/opensta_expts/test] get_ports
_90a3be344e560000_p_Port _90a0be344e560000_p_Port _109fbe344e560000_p_Port _209dbe344e560000_p_Port _7095be344e560000_p_Port _7094be344e560000_p_Port
sta [~/opensta_expts/test] get_nets
_f0a2e6334e560000_p_Net _709c8d354e560000_p_Net _a0b7e6334e560000_p_Net _c0c4e6334e560000_p_Net _a090e6334e560000_p_Net _f025e6334e560000_p_Net _4065e6334e560000_p_Net _c035e6334e560000_p_Net _f00ee6334e560000_p_Net _e060e6334e560000_p_Net
sta [~/opensta_expts/test] 
%%%%%%%%%%

Let me know how can I fix this.

**Comment by tspyrou** [comment]
The names are object pointers not obfuscated. If you use foreach in collection on the list you can call get_name on each element in the list to puts the names.

**Comment by sagarbaba** [comment]
Thank You for the help. The following works.
foreach p [get_ports] { puts [get_name $p]}
