### ISSUE TITLE
Bug:  GraphDelayCalc::loadCap

### ISSUE THREAD

**Issue by yuhan-icb** [parallaxsw/OpenSTA#16]
In this function GraphDelayCalc::loadCap(const Pin *drvr_pin, const DcalcAnalysisPt *dcalc_ap), the initial value of load_cap is 0.0.

If min_max is set to min, load_cap will always be zero. So, is it necessary to use min_max->initValue() instead?

![image](https://github.com/parallaxsw/OpenSTA/assets/122420742/8e4164c1-cfd7-43b7-9e0f-e34c428a03bf)

**Comment by jjcherry56** [comment]
You are correct. Fixed in
4c850afc GraphDelayCalc::loadCap init value
