### ISSUE TITLE
set_load : fail with changed netlist 

### ISSUE THREAD

**Issue by sheblaev** [parallaxsw/OpenSTA#21]
Hi,
I'm trying to get load for net during  buffer insertion. Here is the simple testcase which uses cells from openSTA examples.
------------------------------------
read_liberty          example1_fast.lib
read_verilog          test.v
link_design           test
read_sdc              test.sdc

report_checks         -fields {slew capacitance net} -digits 4
set_load              10.0 {w}

report_checks         -fields {slew capacitance net} -digits 4

disconnect_pin        {w} {buf1/Z}
disconnect_pin        {a} {buf1/A}
delete_instance       {buf1}
make_instance         {buf1} {BUF_X1}
connect_pin           {w} {buf1/Z}
connect_pin           {a} {buf1/A}

report_checks         -fields {slew capacitance net} -digits 4
set_load              10.0 {w}

report_checks         -fields {slew capacitance net} -digits 4

Please note that the first two reports contain correct cap value for the "w" network. But after buffer remove/add and reconnect I get wrong cap in **fourth** report - the third report is correct.

![image](https://github.com/parallaxsw/OpenSTA/assets/9824885/0433379a-0cf1-4da8-a11d-f664896c6659)

![image](https://github.com/parallaxsw/OpenSTA/assets/9824885/e2ccc8aa-5e6a-4c5a-ad5a-4927052de325)

[buffer.tar.gz](https://github.com/parallaxsw/OpenSTA/files/14872625/buffer.tar.gz)

**Comment by jjcherry56** [comment]
fixed by e5774502 set_load after delete_pin issue21
thanks for good test case
