### ISSUE TITLE
BUG: netSlack

### ISSUE THREAD

**Issue by yuhan-icb** [parallaxsw/OpenSTA#25]
For function `Slack Sta::netSlack(const Net *net, const MinMax *min_max)`, use the `pinIterator(net)` will miss some pins, so it may use `connectedPinIterator(net)` for visiting all pins on the net.
![图片](https://github.com/parallaxsw/OpenSTA/assets/122420742/4422ab32-0e16-4359-a5fa-b6684629ad7a)

**Comment by jjcherry56** [comment]
fixed by
22453cc8 Sta::netSlack use connectedPinIterator
