### ISSUE TITLE
define_corners without load crashes

### ISSUE THREAD

**Issue by maliberty** [parallaxsw/OpenSTA#28]
OpenSTA 2.5.0 00c2082003 Copyright (c) 2024, Parallax Software, Inc.
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>

This is free software, and you are free to change and redistribute it
under certain conditions; type `show_copying' for details. 
This program comes with ABSOLUTELY NO WARRANTY; for details type `show_warranty'.
% define_corners
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = sta::Corner*; _Alloc = std::allocator<sta::Corner*>; std::vector<_Tp, _Alloc>::reference = sta::Corner*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)

**Comment by maliberty** [comment]
Fwiw you might want a test like https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/test/commands_without_load.tcl

**Comment by parallaxsw** [comment]
works fine for me

OpenSTA 2.5.0 1160c80837 Copyright (c) 2024, Parallax Software, Inc.
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>

This is free software, and you are free to change and redistribute it
under certain conditions; type `show_copying' for details. 
This program comes with ABSOLUTELY NO WARRANTY; for details type `show_warranty'.
% define_corners
%

**Comment by maliberty** [comment]
Perhaps you don't have range checking enabled.  I see `define_corners_cmd` calls `Sta::makeCorners` which calls `corners_->findCorner(0)`.  The corners_ vector is empty so indexing it with 0 is out of bounds - `Assertion '__builtin_expect(__n < this->size(), true)' failed.`

**Comment by parallaxsw** [comment]
e448ed3d define_corners require at least 1 corner
