### ISSUE TITLE
Truncated help outputs

### ISSUE THREAD

**Issue by nmoroze** [parallaxsw/OpenSTA#29]
I noticed two commands with truncated help outputs, `report_checks` and `with_output_to_variable`.

```
% help report_checks
report_checks [-from from_list|-rise_from from_list|-fall_from from_list]
   [-through through_list|-rise_through through_list|-fall_through through_list]
   [-to to_list|-rise_to to_list|-fall_to to_list] [-unconstrained]
   [-path_delay min|min_rise|min_fall|max|max_rise|max_fall|min_max]
   [-corner corner] [-group_count path_count] [-endpoint_count path_count]
   [-unique_paths_to_endpoint] [-slack_max slack_max] [-slack_min slack_min]
   [-sort_by_slack] [-path_group group_name]
   [-format full|full_clock|full_clock_expanded|short|end|summary]
```

Here I'd expect several additional keys to be included, based on the `define_cmd_args` for this command:  `-fields`, `-digits`, `-no_line_splits`, as well as the redirect operators. 

```
% help with_output_to_variable
with_output_to_variable var
```

This output is missing the `{ cmds }` piece that is included in its `define_cmd_args`.

Issue was originally noted in https://github.com/The-OpenROAD-Project/OpenROAD/issues/5057

**Comment by parallaxsw** [comment]
fixed by
51596f89 help with_output_to_variable
1160c808 help report_checks
