### ISSUE TITLE
synchronizing the arc delay calc

### ISSUE THREAD

**Issue by maliberty** [parallaxsw/OpenSTA#30]
When executing `set_delay_calculator ccs_sim`, Sta::setArcDelayCalc deletes and replaces arc_delay_calc_.  However any other StaState (eg OR's Resizer) has now got a stale pointer in its copy of arc_delay_calc_.

I can solve this by making a registry in dbSta but I suppose this will be a general problem for sta clients.  Do you think it better to build in a mechanism to handle this in sta itself?  Perhaps another level of indirection?

**Comment by parallaxsw** [comment]
There is a mechanism.
Somebody on the ORD side should be calling StaState::updateComponentsState() on the Resizer
(like dbSta).
