### ISSUE TITLE
How to use the gateDelay API without a specific Pin in CCS?

### ISSUE THREAD

**Issue by maliberty** [parallaxsw/OpenSTA#31]
In OR's [Resizer::gateDelays](https://github.com/The-OpenROAD-Project/OpenROAD/blob/1c9637d0f9032694f5a5964ea1e91f77d3cc4aef/src/rsz/src/Resizer.cc#L2187) we call `arc_delay_calc_->gateDelay(nullptr, ...`.  With the default delay calculator this works fine but when switched to CCS it fails.  In CcsSimDelayCalc::gateDelay it [calls](https://github.com/parallaxsw/OpenSTA/blob/abacd6c89c6e80b66a53f92cca613187f7a3223b/dcalc/CcsSimDelayCalc.cc#L145)
```
  Vertex *drvr_vertex = graph_->pinDrvrVertex(drvr_pin);
```
with the nullptr drvr_pin resulting in a nullptr drvr_vertex which is subsequently dereferenced.

What is the recommended way to call this API in the use model that the resizer is operating without a specific Pin to pass?

**Comment by parallaxsw** [comment]
That is dead code. 
I would much rather see the test that demonstrates the problem than an english interpretation.
The debugger can tell me what line of code fails.
Fixed by
f9618418 ccs_ceff, ccs_sim allow null drvr_pin, vdd check
