### ISSUE TITLE
incorrect area reported with get_property

### ISSUE THREAD

**Issue by gadfort** [parallaxsw/OpenSTA#34]
When getting the area of a liberty cell via `get_property` it returns `1` regardless of cell size.

I've attached a testcase:
[test.tar.gz](https://github.com/parallaxsw/OpenSTA/files/15491729/test.tar.gz)

```
tar xvf test.tar.gz
cd test
sta test.tcl
```

Reports:
```
Area: 1
```

But should have been:
```
Area: 27.526400000
```

**Comment by parallaxsw** [comment]
fixed by
49c713e4 issue34 get_property liberty_cell area

**Comment by parallaxsw** [comment]
fixed by
49c713e4 issue34 get_property liberty_cell area
