### ISSUE TITLE
get_pins segfaults with non-string property as filter

### ISSUE THREAD

**Issue by gadfort** [parallaxsw/OpenSTA#36]
The issue I'm running into was trying to find the register_clock pin on a cell. So there might be two issues going on:
1. when calling `get_pins -of_object $cell -filter is_register_clock==1` the tool segfaults (see the attached test case).
2. non-string values such as is_register_clock is not meant to be supported by `-filter`, if that is the case, I think it would be a nice enhancement, if possible?

Test case: [test_pin_filter.tar.gz](https://github.com/user-attachments/files/15518059/test_pin_filter.tar.gz)
```
tar xvfz test_pin_filter.tar.gz
cd test_pin_filter
sta test.v
```

It should output:
```
OpenSTA 2.5.0 e01d3f163f Copyright (c) 2024, Parallax Software, Inc.
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>

This is free software, and you are free to change and redistribute it
under certain conditions; type `show_copying' for details. 
This program comes with ABSOLUTELY NO WARRANTY; for details type `show_warranty'.
dut
dut/CK
is_register_clock 1
Segmentation fault
```

**Comment by parallaxsw** [comment]
makes sense to me. add by
f24d907b get_* -filter property==non_string_value
