### ISSUE TITLE
core dumped in ccs_sime1.tcl

### ISSUE THREAD

**Issue by icesdu** [parallaxsw/OpenSTA#38]
Hello developer,When I execute the `ccs_sim1.tcl` file in the official test directory, a core dump occurs when it reaches the eighth line.May I also ask if you could recommend some materials on CCS algorithms?
![image](https://github.com/parallaxsw/OpenSTA/assets/119279996/136e66bf-18e4-4499-98fa-4b2f51d7a452)

**Comment by parallaxsw** [comment]
fixed by
e81d3c5d issue38 ccs_sim1
