### ISSUE TITLE
general report_checks to ROM ADDR pin does not report path identified to same pin through a report_checks through a specific source flop

### ISSUE THREAD

**Issue by markv-as2inc** [parallaxsw/OpenSTA#4]
Using a newly built sta:
OpenSTA 2.4.0 96348ebe58 Copyright (c) 2021, Parallax Software, Inc.
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>

from git clone https://github.com/parallaxsw/OpenSTA.git

This "general" search using report_checks to the ROM ADDR[0] pin:
foreach romAD {
	X23547/ADDR[0]	\
} { report_checks -to $romAD -endpoint_count 2048 -group_count 2048 -format full_clock_expanded }

reports 388 different paths  (well below the 2048 limits identified.)  With slacks ranging from -1387.26 to 814.28  But none
from or through the flop: MI24976/MI25137/X15195_137/Q

However, this specific search, using report_checks to the same ROM ADDR[0] pin, but identifying a known source flop:

report_checks -through MI24976/MI25137/X15195_137/Q -to X23547/ADDR[0]  -endpoint_count 512 -format full_clock_expanded

reports with slacks either -186.22, or 37.78 depending on the clock edges, which are between -1387 and 814.  

Thus it appears that the list of sources for the general search to this common endpoint is omitting the source flop of the
specific search, and thus not providing data required by anyone trying to understand what the sources affecting the address are.

I have attached at gzipped tar file with files that demonstrate this issue.

It should run with 
$ sta
% source run_test.tcl

which will write two report files:

report_checks.to.ROM_ADDR.AX.AY.out    ----- this is the general report output, missing the X15195_137 source
report_checks.from.X15195_137.out          ----   this is the specific report output, only showing that it can be traced

If I have still not used the right version of OpenSTA, or you need more details on this test, please let me know.  Thanks for your attention to this issue.
[toOpenSTA.tar.gz](https://github.com/parallaxsw/OpenSTA/files/12402727/toOpenSTA.tar.gz)

**Comment by markv-as2inc** [comment]
It appears that there are several more flops that are similarly not reported:  MI24976/MI25137/MI889/Q, MI24976/MI25137/MI333/Q, which I can identify tracing the clock path for X15195_137.

**Comment by markv-as2inc** [comment]
This form of report_checks, seems to always yield 4 paths, even when there are many more flops on this clock:

report_checks -from [get_clocks X18946_1032 ] -to [get_pins  X23547/ADDR[0] ]  -endpoint_count 2048 -group_count 2048 -format full_clock_expanded

starts with either rising or falling edge, and ends with either ADDR.0 rising or falling, making 4, but not exploring any other flops

**Comment by markv-as2inc** [comment]
My analysis says there are 1621 flops on the fanout of X18946_1032 using:

foreach inst [get_fanout -from MI24976/MI24335/X18946_1032/Q -flat -only_cells -endpoints_only ] {
	puts [probe inst [get_full_name $inst ]]
}

where probe inst yields:

cmd=<probeInst MI24976/MI1326/MI177>
SC_DFC_34_26D2 MI24976/MI1326/MI177 (
	.IQ	( no net found ),
	.IQN	( no net found ),
	.GS1	(GND),
	.VS	(R25_PLUS),
	.GS	(N1224_S),
	.CPN	(MI24976/MI1326/X1115_24_CPN),
	.CPP	(MI24976/MI1326/X1115_24_CPP),
	.Q	(T_0395),
	.VS1	(X17722_VS),
	.D	(MI24976/MI1326/X274631_588_ZN),
	.CDN	(MI24976/MI24901_RST0N_OUT[269]),
	);

**Comment by jjcherry56** [comment]
I am not going to look into this until you confirm that the issue persists after using updated liberty files.

**Comment by markv-as2inc** [comment]
James,
I did update the library files, and this issue seems to have been resolved. I am very grateful for that help. I do recommend some messages about the missing timing_type : positive_edge; issue.

I am now having trouble with no timing paths coming out of the rom-like cell:  CORE_HIER_behav, on the DOUT0[34:0] and DOUT1[35:0] outputs.

The model does seem to get the clock on the CPN pin, and reports setup/hold issues on the ADDR, AX0, AY0, AY1 inputs, which are also busses.  But I have put an extra test_flop_1 directly on DOUT0[17], and I continue
to get "No Paths" as the
     report_checks -to [get_cells test_flop_1 ]
result.

 I did "correct" the ROM's model to have

ff_bank ( IQ, IQN, 36 ) {
                        next_state : CTRL_D ;
                        clocked_on : CPN ;
                        clock_type : posedge;
                }

Instead of just ff (IQ, IQN){...  which is in the library I think I sent before.  I have attached my latest one to this email.

So, I suspect that the CORE_HIER_behav library element is still missing some sort of liberty construct too.

The output busses are coded as follows:

                bus ( DOUT0 ) {
                        direction       : output;
                        function        : IQ ;
                        bus_type        : bus35;
                        timing () {
                                timing_type     : rising_edge;
                                intrinsic_rise  : 0.1 ;
                                intrinsic_fall  : 0.1 ;
                                rise_resistance : 1.6800 ;
                                fall_resistance : 1.8600 ;
                                related_pin     : CPN ;
                        }

                }

with the bus defined as follows:

                type ( bus35) {
                        base_type       : array;
                        data_type       : bit;
                        bit_width       : 35 ;
                        bit_from        : 34 ;
                        bit_to          : 0 ;
                        downto          : true ;
                }

If you have any insight explaining why the timing path out of this ROM is not being reported, I would welcome it.

Thanks!

Mark Vancura
________________________________

**Comment by markv-as2inc** [comment]
These are the flops I added to the TOP_HIER module, to be sure I had a path that was not disabled.

// test flops
SCD_DFC_36_32D2 test_flop_1 (
        .VS1    (X17722_VS),
        .GS1    (GND),
        .Q      (test_flop_Q),
        .VS     (R25_PLUS),
        .CDN    (X5453_ZN),
        .GS     (N1224_S),
        .CP     (MI24659_A2[4]),
        .D      (CORE_DOUT0[17])
        );
SCD_DFC_36_32D2 test_flop_2 (
        .VS1    (X17722_VS),
        .GS1    (GND),
        .Q      (test_flop_Q2),
        .VS     (R25_PLUS),
        .CDN    (X5453_ZN),
        .GS     (N1224_S),
        .CP     (MI24659_A2[4]),
        .D      (test_flop_Q)
        );


endmodule // TOP_HIER

________________________________

**Comment by jjcherry56** [comment]
You are going to have to attach an updated testcase to the github issue (email attachments to get through).

**Comment by markv-as2inc** [comment]
James,
Thanks I appreciate your reply. I did try several that were rejected because the library was too big, so I need to make one with a smaller library.

Mark Vancura
________________________________

**Comment by jjcherry56** [comment]
you could try sharing a tarfile on google drive to c h e r r y at parallax sw dot com
