### ISSUE TITLE
Genclks can't exit BfsBkwdIterator

### ISSUE THREAD

**Issue by eaglechip** [parallaxsw/OpenSTA#41]
Hello，I am testing the sdc "create_generated_clock".   When  I add create_generated_clock like following, the OpenSTA app can't correctly return。please help to fix it when you are available，thank you！

I add the sdc in the examples file(/OpenSTA-master/examples/delay_calc.tcl) like this:
create_generated_clock -name gclk -source [get_pins r1/CK] -divide_by 2 [get_pins r1/Q]

![gen_clk](https://github.com/parallaxsw/OpenSTA/assets/171646321/d180db88-f177-478b-bb3e-48d80f68548d)

the run result is:
![run_reslt](https://github.com/parallaxsw/OpenSTA/assets/171646321/0b9b6768-41ca-4b6b-b8b9-2b899c65e610)

**Comment by parallaxsw** [comment]
87816b30 issue41 genclk master search
