### ISSUE TITLE
Use resize many places, should use reserve instead.

### ISSUE THREAD

**Issue by icbenchpeng** [parallaxsw/OpenSTA#5]
void
Corners::copy(Corners *corners)
{
  clear();
  int index = 0;
  for (Corner *orig : corners->corners_) {
    const char *name = orig->name();
    Corner *corner = new Corner(name, index);
    corners_.push_back(corner);
    // Use the copied name in the map.
    corner_map_[corner->name()] = corner;
    index++;
  }
  makeAnalysisPts();
  
  for (ParasiticAnalysisPt *orig_ap : corners->parasitic_analysis_pts_) {
    ParasiticAnalysisPt *ap = new ParasiticAnalysisPt(orig_ap->name(), orig_ap->index(),
						      orig_ap->minMax());
    parasitic_analysis_pts_.push_back(ap);
  }

  int i = 0;
  for (Corner *orig : corners->corners_) {
    Corner *corner = corners_[i];
    auto &orig_aps = orig->parasitic_analysis_pts_;
    auto &corner_aps = corner->parasitic_analysis_pts_;
    corner_aps.**resize**(orig_aps.size());  **// resize should be reserve here ?**
    for (ParasiticAnalysisPt *orig_ap : orig_aps) {
      int ap_index = orig_ap->index();
      corner_aps.**push_back**(parasitic_analysis_pts_[ap_index]);
    }
    i++;
  }
}

Please check all relative usage.

**Comment by jjcherry56** [comment]
In this case reserve is indeed correct because push_back is used. The other cases index the vector instead of push_back so they are correct.
29b94cc Corners::copy use copy constructor for parasitic_analysis
