### ISSUE TITLE
Add tcl get methods for power information

### ISSUE THREAD

**Issue by maliberty** [parallaxsw/OpenSTA#53]
In https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/2163 we need to be able to get the information from report_power in a TCL so that we can perform some checks.  I see no commands in sta to do this.

**Comment by akashlevy** [comment]
`sta::design_power [sta::parse_corner {}]` should do the trick

**Comment by akashlevy** [comment]
You can replace `{}` with `keys` containing `corner` if you have a particular corner. A little hacky but this is what's called by `report_power` under the hood

**Comment by jjcherry56** [comment]
Akash is correct. These functions have been there all along. Use sta::cmd_corner to get the default command corner or sta::find_corner for a specific corner rather than the arg parsing functions.
