### ISSUE TITLE
Sta::isDisabledClock does not have an implementation

### ISSUE THREAD

**Issue by tsyw** [parallaxsw/OpenSTA#6]
Hi, 
I want to build OpenSTA using Swig to generate a Python Interface. But the generated CXX file and .so file cannot be used because this method does not have an implementation.
I tried to understand the comment. But I don't know what the prpath is.
Here is the comment:
"// Edge is disabled to prpath a clock from propagating." 

My current workaround solution is deleting this declaration for building process.

**Comment by jjcherry56** [comment]
I deleted the prototype.
