### ISSUE TITLE
Why Ceff is 0？

### ISSUE THREAD

**Issue by icesdu** [parallaxsw/OpenSTA#65]
This seems to be a bug. When I run my simple example, the report_dcalc command shows that both c and r are 0. However, when I use primetime, there are values.
![image](https://github.com/user-attachments/assets/729deb92-292a-48e8-a60f-5fd9b9bb8269)

**Comment by jjcherry56** [comment]
perhaps. But I can't help you without a testcase. I am not going to type in the files from an image and there a liberty file is required.

**Comment by icesdu** [comment]
I have identified the issue: the problem lies in the fact that the values in the SPEF file are relatively small, and the report can only display two decimal places of the library units. It cannot automatically convert units or display more decimal places. I think this could lead to the report being less intuitive and detailed.

**Comment by jjcherry56** [comment]
-digits arg to reporting commands. rtfm
