### ISSUE TITLE
Memory leak in `report_power`

### ISSUE THREAD

**Issue by akashlevy** [parallaxsw/OpenSTA#71]
With the recent changes enabling CUDD universally, `report_power` appears to be leaking memory pretty badly. This can be reproduced by simply rerunning `report_power` many times. A system will quickly run out of memory even on a small design.

Here's a simple test case showcasing the problem. I tested this as `test/report_power_memleak.tcl`. Running this blows up to ~30GB of RAM in <2000 iterations on my MacBook Pro M2.

```
read_liberty ../examples/sky130hd_tt.lib
read_verilog ../examples/gcd_sky130hd.v
link_design gcd
for {set i 0} {$i < 2000} {incr i} {
  report_power
}
```

Let me know if you have any insights on why this is happening and how to fix...

**Comment by jjcherry56** [comment]
This should be fixed by
9d259796 cudd usage memory leak

**Comment by akashlevy** [comment]
Thanks Cherry. I'll give it a try in a bit

**Comment by akashlevy** [comment]
Works great, thank you
