### ISSUE TITLE
UPF support for `report_power`

### ISSUE THREAD

**Issue by akashlevy** [parallaxsw/OpenSTA#81]
Are there any near-term plans to add support for UPF during power analysis?

I could potentially contribute this if there is interest.

**Comment by QuantamHD** [comment]
UPF is being implemented in OpenROAD. Were you planning on using the interface there, and propagating it to OpenSTA?

I think it would be unfortunate if we ended up with two implementations with slightly different capabilities.

**Comment by QuantamHD** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/tree/master/src/upf

**Comment by akashlevy** [comment]
I think implementing UPF mainly on the OpenROAD side makes sense. Many of the UPF commands don't even make much sense in OpenSTA, like the retention cell specs, etc...

But probably a few of the commands need to be implemented in OpenSTA to enable domain-aware power analysis. Specifically, I'm thinking about the commands that define power domains, power nets, power switches, and power state tables. I'd like to see it possible to do domain-aware + state-aware power analysis in OpenSTA without having to use OpenROAD. And it would be great if OpenROAD relied on OpenSTA's ability to handle power domains/switches/tables during power analysis

**Comment by akashlevy** [comment]
Does it make sense to upstream some of the UPF functions that don't have strong dependences on `odb`? Or is it somewhat difficult to extricate that in the OR UPF implementation?

**Comment by QuantamHD** [comment]
I think this might be a case where it needs to implemented similarly to the network interface, where a downstream user can provide their own storage object/implementation which in the case of OpenROAD would be backed by ODB and in OpenSTA you can provide a "ConcreteImplementation".

I think a nice property of the OpenROAD UPF implementation is that the UPF data is persisted in its database, and if you move some of the implementation over to OpenSTA we will lose that property and worse it'll be mixed.

If it were up to me (it's not) I would suggest making the abstract network like UPF that OpenROAD can integrate with, and then you provide your own ConcreteImplementation and provide TCL layer in OpenSTA that can be turned off for OpenROAD that implements the commands you want.

**Comment by QuantamHD** [comment]
Also @jjcherry56 should weigh in since ultimately he decides what goes into OpenSTA

**Comment by akashlevy** [comment]
> I think this might be a case where it needs to implemented similarly to the network interface, where a downstream user can provide their own storage object/implementation which in the case of OpenROAD would be backed by ODB and in OpenSTA you can provide a "ConcreteImplementation".

That sounds like a nice solution to me, personally... curious to hear Cherry's thoughts

**Comment by jjcherry56** [comment]
The OpenSTA Network interface implements what is known as an "adapter" pattern (see Design Patterns: Elements of Reusable Object-Oriented Software). I agree that this is the right way to handle this.

**Comment by maliberty** [comment]
It would be helpful if you defined what specific commands you intend to implement and how they would be exposed to OR in the Network API.

**Comment by akashlevy** [comment]
Hi Matt, I'll have to dive deeper into how the network API works first, as I haven't used it myself yet. The UPF commands that probably make sense to have concrete implementations for in OpenSTA:

(Implemented in OR already)
- `create­_po­wer­_domain`
- `create_logic_port`
- `create_power_switch`
- `set_isolation`
- `set_domain_voltage`

(Not implemented in OR yet afaik and probably lower priority: updating port attrs, isolation control, retention+control, PST)
- `set_port_attributes`
- `set_isolation_control`
- `set_retention`
- `set_retention_control`
- `add_port_state`
- `create_pst`
- `add_pst_state`

In the short term, to get some very rough domain-aware power analysis working, it could make sense to just assume ideal power switches/interface/shifter cells; long term, support could be added for using Liberty cell characteristics thru commands like:

- `use_interface_cell`
- `map_power_switch`
- `set_level_shifter`, `set_level_shifter_cell`

**Comment by maliberty** [comment]
Why would set_isolation or create_power_switch make sense to sta?

**Comment by maliberty** [comment]
The power switches defined in UPF are only logical and not physical instances.  From the spec:

```
The create_power_switch command defines an abstract model of a power switch. An implementation may 
use detailed power-switching structures that involve multiple, distributed power switches in place of a 
single abstract power switch, and/or re-order the specified embedded power switch chain. 
```

Perhaps the difference doesn't matter to sta but it does matter to OR.  Since sta uses a network adapter I don't think it can see a divergent view.

**Comment by akashlevy** [comment]
Yeah, I mean any command that affects the power netlist will need to have a concrete implementation in whichever tool is hosting the netlist. So if OR is hosting, it should obviously provide its own concrete implementation of `create_power_switch`. And if OpenSTA is hosting, `sta` should provide its own concrete implementation; I'm thinking this could either be by using the edit API to add an inferred power switching Liberty cell into the STA network or something simpler like storing information about the switch's control port in a data structure for power analysis.

I guess we may end up with a lot of places where the implementations diverge, but that's to be expected... UPF has a different meaning when analyzing power vs. using it as power intent for physical design.

**Comment by akashlevy** [comment]
I'll come up with some ideas on how to reuse as much as possible though. I need to study the OR UPF implementation and the network API in a bit more detail before I can do so in an intelligent way

**Comment by akashlevy** [comment]
I did a bit more thinking/research and I think I've come to agree with @QuantamHD that it makes most sense to have UPF processed prior to OpenSTA power analysis. Basically use UPF to construct a power netlist (or pseudo power netlist) and have OpenSTA handle the power analysis as usual once that's done. So I'm going to close this issue for now. If there's interest in native UPF support + power netlist construction in OpenSTA, we can potentially re-open this issue in the future
