### ISSUE TITLE
Segv related to reporting user error related to max_clock_tree_path

### ISSUE THREAD

**Issue by maliberty** [parallaxsw/OpenSTA#88]
A trivial reproducer for the crash that was mentioned in #87 

`sta bug.tcl` to reproduce.

The test is reduced from a user error that generates the segv while reporting the error.
[bug.zip](https://github.com/user-attachments/files/16984289/bug.zip)

@oharboe FYI

**Comment by jjcherry56** [comment]
fixed by
41fe4d28 issue88 missing arc warning for liberty clock tree path

**Comment by oharboe** [comment]
> fixed by [41fe4d2](https://github.com/parallaxsw/OpenSTA/commit/41fe4d284446cc11802154deefe120d8090c47ea) issue88 missing arc warning for liberty clock tree path

Thanks!
