### ISSUE TITLE
Typo in  search/CheckCapacitanceLimits.cc, line 182

### ISSUE THREAD

**Issue by sheblaev** [parallaxsw/OpenSTA#9]
Please check search/CheckCapacitanceLimits.cc, line 182

Current: 
 if (!exists1
              && corner_port->direction()->isAnyOutput()
              && min_max == MinMax::max())
            corner_port->libertyLibrary()->defaultMaxSlew(limit1, exists1);

---------------------------------------------------
Please check if the typo is here. I believe the code should use  defaultMaxCapacitance(), not defaultMaxSlew() here.

 if (!exists1
              && corner_port->direction()->isAnyOutput()
              && min_max == MinMax::max())
            corner_port->libertyLibrary()->defaultMaxCapacitance(...);

**Comment by jjcherry56** [comment]
Thanks for the heads up.
Fixed in 88c49f1e  CheckCapacitanceLimits::findLimit library default
