### ISSUE TITLE
Why doesn't my Tab hava autocomplete?

### ISSUE THREAD

**Issue by gjy1223** [parallaxsw/OpenSTA#92]
This is opensta terminal.
![image](https://github.com/user-attachments/assets/89d627a6-3d13-4581-b8d1-b15c517e9232)

This is my terminnal.
![image](https://github.com/user-attachments/assets/c4784e33-3361-4a29-a823-409272cb1fd0)

This is my linux version.
![image](https://github.com/user-attachments/assets/9e4b5266-cefe-4c88-a719-14247c6004cd)

Please help me. Thank you.

**Comment by akashlevy** [comment]
You need `tclreadline`. On Ubuntu: `sudo apt-get install tcl-tclreadline`

**Comment by gjy1223** [comment]
![image](https://github.com/user-attachments/assets/7236c5e6-3235-4ea1-a799-a971f59ffc27)
yes！！！！It is work success. Thank you so much. Lol
