### ISSUE TITLE
CUDD: optional or required?

### ISSUE THREAD

**Issue by GTP95** [parallaxsw/OpenSTA#93]
Greetings,

I'm trying to build this project, but there's an inconsistency in the README's instructions. In the external library dependencies table, CUDD is indicated as a required dependency. But subsequent text in the README identifies it as an optional dependency. Furthermore, when invoking `cmake`, it fails with an error telling me I need to set `CUDD_LIB`. 
Could you please tell me if it is required or not? If not, how can I build this project without it?
Thank you for your help,

GTP

**Comment by GTP95** [comment]
My main issue was that the first link provided for CUDD is broken, while the second doesn't contain build instructions. I was able to build CUDD by following the instructions reported [here](https://github.com/ivmai/cudd), then to build OpenSTA by providing the path to CUDD. But I would still suggest fixing the inconsistency in the README and, if possible, update the link to CUDD to [this](https://github.com/ivmai/cudd), as it also has build instructions.

**Comment by maliberty** [comment]
Fwiw I put a copy of CUDD at https://github.com/The-OpenROAD-Project/cudd.  I believe it is required now.

**Comment by jjcherry56** [comment]
CUDD changed to required with OpenSTA 2.6.0, so cmake should fail if CUDD_DIR is not set.
I updated the readme to point to the current maintainer's url.
The CUDD readme has build instructions in it.
